name: httprunner
base: core22
version: git
summary: Execute HTTP requests from .http files with colored output
description: |
  HTTP File Runner is a command-line tool written in Zig for parsing and 
  executing HTTP requests from .http files. Features include:
  
  • Support for GET, POST, PUT, DELETE, PATCH methods
  • Color-coded output with emojis for success/failure indication
  • Custom headers support
  • Detailed error reporting with status codes
  • Summary statistics
  • Robust network error handling

grade: stable
confinement: strict

apps:
  httprunner:
    command: bin/httprunner
    plugs:
      - network
      - home

parts:
  zig:
    plugin: nil
    build-packages:
      - curl
      - xz-utils
    override-build: |
      ZIG_VERSION="0.14.1"
      curl -L "https://ziglang.org/download/${ZIG_VERSION}/zig-x86_64-linux-${ZIG_VERSION}.tar.xz" -o zig.tar.xz
      tar -xf zig.tar.xz
      mkdir -p $SNAPCRAFT_PART_INSTALL/zig
      cp -r zig-x86_64-linux-${ZIG_VERSION}/* $SNAPCRAFT_PART_INSTALL/zig/

  httprunner:
    after: [zig]
    plugin: nil
    source: .
    override-build: |
      export PATH="$SNAPCRAFT_STAGE/zig:$PATH"
      zig build -Doptimize=ReleaseFast
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp zig-out/bin/httprunner $SNAPCRAFT_PART_INSTALL/bin/
    stage-packages:
      - libc6
