name: httprunner
base: core24
version: v0.6.45
summary: Execute HTTP requests from .http files with colored output
description: |
  HTTP File Runner is a command-line tool written in Rust for parsing and 
  executing HTTP requests from .http files. Features include:

  • Support for GET, POST, PUT, DELETE, PATCH methods
  • Color-coded output with emojis for success/failure indication
  • Custom headers support
  • Detailed error reporting with status codes
  • Summary statistics
  • Robust network error handling

title: HTTP File Runner
contact: https://github.com/christianhelle/httprunner/issues
issues: https://github.com/christianhelle/httprunner/issues
source-code: https://github.com/christianhelle/httprunner
website: https://christianhelle.com/httprunner
donation: https://buymeacoffee.com/christianhelle

grade: stable
confinement: strict
license: MIT

apps:
  httprunner:
    command: bin/httprunner
    plugs:
      - network
      - home

parts:
  httprunner:
    plugin: rust
    source: .
    rust-channel: stable
    build-packages:
      - libssl-dev
      - pkg-config
      - git
    stage-packages:
      - libssl3
      - ca-certificates
