name: httprunner
base: core24
version: v0.6.45
summary: Execute HTTP requests from .http files - CLI and GUI tools
description: |
  HTTP File Runner is a suite of tools written in Rust for parsing and 
  executing HTTP requests from .http files. Includes both a command-line 
  tool and a native GUI application. Features include:

  • Support for GET, POST, PUT, DELETE, PATCH methods
  • Color-coded output with emojis for success/failure indication
  • Custom headers support
  • Detailed error reporting with status codes
  • Summary statistics
  • Robust network error handling
  • Native GUI with file browser and request inspector

title: HTTP File Runner
contact: https://github.com/christianhelle/httprunner/issues
issues: https://github.com/christianhelle/httprunner/issues
source-code: https://github.com/christianhelle/httprunner
website: https://christianhelle.com/httprunner
donation: https://buymeacoffee.com/christianhelle

grade: stable
confinement: strict
license: MIT

apps:
  httprunner:
    command: bin/httprunner
    plugs:
      - network
      - home
  
  httprunner-gui:
    command: bin/httprunner-gui
    desktop: snap/gui/httprunner-gui.desktop
    plugs:
      - network
      - home
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl
      - pulseaudio

parts:
  httprunner:
    plugin: rust
    source: .
    rust-channel: stable
    build-packages:
      - libssl-dev
      - pkg-config
      - git
      - libxcb-render0-dev
      - libxcb-shape0-dev
      - libxcb-xfixes0-dev
      - libxkbcommon-dev
      - libwayland-dev
      - libfontconfig1-dev
    stage-packages:
      - libssl3
      - ca-certificates
      - libxcb1
      - libxcb-render0
      - libxcb-shape0
      - libxcb-xfixes0
      - libxkbcommon0
      - libwayland-client0
      - libwayland-cursor0
      - libfontconfig1
      - libfreetype6
    override-build: |
      # Build both CLI and GUI binaries
      cargo build --release --workspace
      
      # Verify binaries were built successfully
      if [ ! -f target/release/httprunner ]; then
        echo "Error: CLI binary not found"
        exit 1
      fi
      if [ ! -f target/release/httprunner-gui ]; then
        echo "Error: GUI binary not found"
        exit 1
      fi
      
      # Install binaries
      install -Dm755 target/release/httprunner $CRAFT_PART_INSTALL/bin/httprunner
      install -Dm755 target/release/httprunner-gui $CRAFT_PART_INSTALL/bin/httprunner-gui
