name: httprunner
base: core22
version: v0.5.36
summary: Execute HTTP requests from .http files with colored output
description: |
  HTTP File Runner is a command-line tool written in Rust for parsing and 
  executing HTTP requests from .http files. Features include:

  • Support for GET, POST, PUT, DELETE, PATCH methods
  • Color-coded output with emojis for success/failure indication
  • Custom headers support
  • Detailed error reporting with status codes
  • Summary statistics
  • Robust network error handling

title: HTTP File Runner
contact: https://github.com/christianhelle/httprunner/issues
issues: https://github.com/christianhelle/httprunner/issues
source-code: https://github.com/christianhelle/httprunner
website: https://christianhelle.com/httprunner
donation: https://buymeacoffee.com/christianhelle

grade: stable
confinement: strict
license: MIT

apps:
  httprunner:
    command: bin/httprunner
    plugs:
      - network
      - home
  httprunner-gui:
    command: bin/httprunner-gui
    plugs:
      - network
      - home
      - x11
      - wayland
      - desktop
      - desktop-legacy

parts:
  httprunner:
    plugin: rust
    source: .
    override-build: |
      set -eux
      # install rustup if missing
      if ! command -v rustup >/dev/null 2>&1; then
        if command -v curl >/dev/null 2>&1; then
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        else
          apt-get update
          apt-get install -y curl
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        fi
      fi
      source $HOME/.cargo/env || true
      rustup toolchain install stable
      rustup default stable
      cd src/cli
      cargo install --locked --path . --root $SNAPCRAFT_PART_INSTALL --force
    build-packages:
      - libssl-dev
      - pkg-config
      - git
      - curl
      - build-essential
    stage-packages:
      - libssl3
      - ca-certificates
  httprunner-gui:
    plugin: rust
    source: .
    override-build: |
      set -eux
      cd src/gui
      # install rustup if missing
      if ! command -v rustup >/dev/null 2>&1; then
        if command -v curl >/dev/null 2>&1; then
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        else
          apt-get update
          apt-get install -y curl
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        fi
      fi
      source $HOME/.cargo/env || true
      rustup toolchain install stable
      rustup default stable
      cargo install --locked --path . --root $SNAPCRAFT_PART_INSTALL --force
    build-packages:
      - libssl-dev
      - pkg-config
      - git
      - curl
      - build-essential
    stage-packages:
      - libssl3
      - ca-certificates
  rust-deps:
    plugin: nil
    build-packages:
      - cargo
      - rustc
