###
# POST request with body (fully supported)
# @name request1
POST https://httpbin.org/post
Content-Type: application/json

{
    "guid": "guid()",
    "GUID": "GUID()",
    "string": "string()",
    "STRING": "STRING()",
    "number": "number()",
    "NUMBER": "NUMBER()",
    "to_base64": "base64_encode('Hello, World!')",
    "TO_BASE64": "BASE64_ENCODE('Hello, World!')",
    "first_name": "first_name()",
    "last_name": "last_name()",
    "name": "name()",
    "address": "address()"
}

#
@first_request_guid={{request1.response.body.$.json.guid}}
@first_request_guid_base64=base64_encode('{{first_request_guid}}')


###
# POST request with body (fully supported)
# @name request2
POST https://httpbin.org/post
Content-Type: application/json

{
    "first_request_guid": "{{request1.response.body.$.json.guid}}",
    "first_request_guid_variable": "{{first_request_guid}}",
    "first_request_guid_variable_base64": "{{first_request_guid_base64}}",
    "first_request_guid_base64": "base64_encode('{{request1.response.body.$.json.guid}}')",
    "guid": "guid()",
    "GUID": "GUID()",
    "string": "string()",
    "STRING": "STRING()",
    "number": "number()",
    "NUMBER": "NUMBER()",
    "to_base64": "base64_encode('{{request1.response.body.$.json.guid}}')",
    "TO_BASE64": "BASE64_ENCODE('{{request1.response.body.$.json.guid}}')",
    "first_name": "first_name()",
    "last_name": "last_name()",
    "name": "name()",
    "address": "address()"
}
